FROM node:20-bullseye-slim AS builder

WORKDIR /app

COPY package*.json ./
COPY nest-cli.json ./
COPY tsconfig*.json ./
COPY jest.base-config.ts ./
COPY libs/ libs/
COPY apps/proj-docs/ apps/proj-docs/

RUN npm install

RUN npx nest build projector

FROM node:20-bullseye-slim

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3001

CMD ["node", "dist/apps/proj-docs/main.js"]
