FROM node:20-bullseye-slim AS builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY api-server/ api-server/

RUN npm install

RUN npm run build:api-server

FROM node:20-bullseye-slim

WORKDIR /app

COPY --from=builder /app/dist/api-server/src ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

CMD ["node", "dist/main.js"]
