FROM node:20-bullseye-slim AS builder

WORKDIR /app

COPY package*.json ./
COPY nest-cli.json ./
COPY tsconfig*.json ./
COPY jest.base-config.ts ./
COPY libs/ libs/
COPY apps/sync-index/ apps/sync-index/

RUN npm install

RUN npx nest build sync

FROM node:20-bullseye-slim

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3002

CMD ["node", "dist/apps/sync-index/main.js"]
