openapi: 3.0.0
paths: {}
info:
  title: API 명세서
  description: CQRS 시스템 설계/구축 챌린지 - API 명세서
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas: {}
